### ISSUE TITLE
Unleash the full power of Remarkable with preset definitions

### ISSUE THREAD

**Issue by p-j** [InsidersByte/react-markdown-renderer#8]
Hi,

I've made a proof of concept real quick because I needed to ship in production with the `++underlined words++` that you can check here : https://github.com/vizeat/react-markdown-renderer/commit/9d2852e0cd14d2ce27ddf151d90e323c00a0e849

The idea is simply to make it possible to specify both the options and the preset when instantiating Remarkable (see [here](https://github.com/jonschlinkert/remarkable/blob/master/lib/index.js#L45-L57) for the relevant code in Remarkable's code base)

Is that something you would consider ? Would you like me to make a PR for that ?
In my case I took the liberty to rename `options` to `remarkableOpts` to make it obvious what it is for and avoid the weird `options.options` or variable renaming at validation/instanciation time. Is that something you would rather avoid ? Doing so would likely require a major version bump due to the breaking change.

Another solution would be to have 2 props passed to the component (options like now and preset) but I'm not found of polluting the parent component with props specific to the internal setup of the child component.

Thanks !

**Comment by InsidersByte** [comment]
:wave:

This is definitely something I want to add support for, thanks for creating the issue!

I would prefer not to rename `options` to `remarkableOpts`, this is because I don't think that `remarkable` should be in the prop name, in the (unlikely) event that the markdown parser is changed or multiple are supported in the future.

> I used to use [marked](https://github.com/chjj/marked) as the markdown parser.

I also agree that adding another prop is less than ideal.

I checked out the [options](https://github.com/jonschlinkert/remarkable#options) and I think we can merge them and then use object spreading to select the preset if it exists, this has the added bonus of not requiring a major bump.

What do you think?

If you could create a PR to do this that would be great! :+1: 

> Sorry for the delayed response, I've been on holiday for the last couple of weeks.

**Comment by p-j** [comment]
I'll look into that soon-ish.
Got a lot on my plate at the moment ;)

I agree with you, destructuring to get the preset out looks like a good middle ground.

**Comment by InsidersByte** [comment]
:+1: 

If you don't get a chance, I should have the time to get it done this weekend.

**Comment by p-j** [comment]
:+1: sorry, I was quite busy for the past week.

**Comment by InsidersByte** [comment]
No worries, I took the opportunity to update the docs site as well :+1:
